@startuml post_docs
participant Docs
participant Files
participant Thumbnails
participant Content
participant Reports
Docs --> Files: put
Docs --> Thumbnails: put
Docs --> Content: put
Docs --> Report: put
@enduml

@startuml patch_docs
participant Docs
participant Files
participant Faces
Docs --> Files: patch
Docs --> Thumbnails: put
Docs --> Content: put
Docs --> Faces: put
@enduml